Wrote an assignment hibernate-cascade.
mate-academy/hibernate-cascade pull request #258
Opened 2022-01-13 15:47 UTC by ASelivonchyk

- configured hibernate.cfg.xml;
- added hibernate annotations to POJO models:
  - User -> Comments @OneToMany, CascadeType.SAVE_UPDATE;
  - Comment -> Smiles @OneToMany, no cascade;
  - Message -> MessageDetails @OneToOne, CascadeType.ALL;
- implemented Dao methods;

2022-01-14 06:01 UTC, RomanDubovskyi requested changes

2022-01-14 06:01 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/model/Comment.java
> +    @OneToMany (fetch = FetchType.EAGER)
якщо у нас є смайле 👍🙂🔥 то вони тільки одному коменту можуть належати, чи я їх може поставити на велику кількість коментарів?

2022-01-14 14:36 UTC, ASelivonchyk commented on src/main/java/core/basesyntax/model/Comment.java
> +    @OneToMany (fetch = FetchType.EAGER)
понял.

2022-01-17 12:52 UTC, MaliukDaria approved these changes
👍🏻

2026-05-10 15:30 UTC, closed without merging