Initial commit
mate-academy/hibernate-cascade pull request #65
Opened 2021-01-27 15:26 UTC by Likh-Alex

- Implemented all `Dao` interfaces except `GenericDao`
- Modified all `Model` classes to meet the tests requirements

2021-01-27 15:43 UTC, ivlytvynets approved these changes

2021-01-28 08:28 UTC, Sofasmile requested changes

2021-01-28 08:56 UTC, Likh-Alex commented on src/main/java/core/basesyntax/dao/impl/CommentDaoImpl.java
> +            throw new RuntimeException("Can not create comment: " + entity.getId(), e);
replaced solely with `entity`

2021-01-28 08:56 UTC, Likh-Alex commented on src/main/java/core/basesyntax/dao/impl/CommentDaoImpl.java
> +            if (transaction != null) {
Shame on me, copy paste curse follows me. Fixed everywhere where applicable

2021-01-28 08:56 UTC, Likh-Alex commented on src/main/java/core/basesyntax/dao/impl/MessageDetailsDaoImpl.java
> +            throw new RuntimeException("Can not create MessageDetails: " + entity.toString());
Understood, thank you. Done as suggested

2021-01-28 08:56 UTC, Likh-Alex commented on src/main/java/core/basesyntax/dao/impl/SmileDaoImpl.java
> +            throw new RuntimeException("Can not create comment: " + entity.toString(), e);
Done, thank you

2021-01-28 08:56 UTC, Likh-Alex commented on src/main/java/core/basesyntax/dao/impl/SmileDaoImpl.java
> +            if (transaction != null) {
Done, thank you

2021-01-28 09:21 UTC, Sofasmile approved these changes

2022-12-21 21:30 UTC, closed without merging